- hosts: "{{ host_group }}"
  gather_facts: False
  vars:
    selected_user_group: "{{ user_group }}"
    ansible_python_interpreter: /usr/bin/python3
    users_default_shell: /bin/bash
    users_create_homedirs: true
  vars_files:
    - ./vars/user_group.yml

  tasks:
    - set_fact:
        users: []

    - name: Setup users
      set_fact:
        users: "{{ users + [ fruits[item.1] ]  }}"
      with_subelements:
        - "{{ group_list }}"
        - members
      when: "item.0.name == selected_user_group"

    - debug:
        var: users

    - name: User creation
      user:
        name: "{{item.username}}"
        # empty string removes user from all secondary groups
        groups: "{{item.groups | join(',') if 'groups' in item else ''}}"
        shell: "{{item.shell if item.shell is defined else users_default_shell}}"
        password: "{{item.password if item.password is defined else '!'}}"
        comment: "{{item.name if item.name is defined else ''}}"
        uid: "{{item.uid | default(omit)}}"
        home: "{{ item.home | default('/home/' + item.username) }}"
        createhome: "{{'yes' if users_create_homedirs else 'no'}}"
        generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
        update_password: "{{item.update_password | default(omit)}}"
      with_items: "{{users}}"

    - name: SSH keys
      authorized_key:
        user: "{{item.username}}"
        state: present
        key: "{{item.ssh_key}}"
      with_items:
        - "{{users}}"
